language: generic

# Dependency of the minted package
before_install:
 - sudo apt-get install python-pygments
install:
 - source ./texlive_install.sh
cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
script:
- bash ./compile_all.sh
# Compile twice to fix references
- bash ./compile_all.sh
before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "frednordell"
      - git config --local user.email "fred@nordells.nu"
      - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  file_glob: true
  file: compiled/*
  skip_cleanup: true
  overwrite: true