language: generic
before_install:
- sudo apt-get install python-pygments
install:
- source ./texlive_install.sh
cache:
  directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"
script:
- bash ./compile_all.sh
- bash ./compile_all.sh
before_deploy:
- git config --local user.name "frednordell"
- git config --local user.email "fred@nordells.nu"
- git tag "$(date +'%Y%m%d')-$(git log --format=%h -1)"
deploy:
  provider: releases
  file_glob: true
  file: compiled/*
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: B5tcWHEQtWAJJYSivLfN4X3pyn9z5pCZuisCCyuhPlHDbv2Xn9+m5ALyXolfAoBfMhFtANMVnfZchYPzdgOXYzLJeKJRiWhK18kNprpFsdzSM3ik/eYA6TVnnVTD4iPZNSUlxyp6sjOYOqfRghpfezsE1//KntoqxjpMG1bH0VYWRgixJeXCAQUPEaGOuxD1VvNkNRcjtNAGav+FrAWBRiZiMIV75nLwBlTXM/pecMQbYDgz1u/0+ZkwVqFRaCo3Fk1wPV2hfrXkz7fiiZc1eLPFsgaL4YMrg6KL246FxOEkdAOUfJEYLovMYYzu5E6+6mAfSbFkxsZ4ozbP5jqZGyqByGbJIWwbApLR+++FOR+ijrwgzo7ZiW7RMjRIGDYcqxUTsIqYdSm0eNO51hCCGUoaYuPXzrb4Mj7Ewne2TsVib5UYBSgtgrpfoXX+Sywg1wvx4810JdnvQB91j0xCcGFa6IAJmvj8nf/U6oJz1eJjrS3oZYywDPOTDumVr0msMf3UV8jeofeS/NVIAOZOgkujfYBGG4HvGm01hM0m9koaYhZz+Gnvchw+dCTZIt2iK9wPul4LL2z+erNOxa1zQyybAQW68/tkCn85YJMf+gJyN3ZClPJCAE8EKsc7Ca7JX14idWlNuGNMxJPp6pixmJRNKoCJFVj6j572qpwlpRg=
