language: generic

# Dependency of the minted package
before_install:
 - sudo apt-get install python-pygments
install:
 - source ./texlive_install.sh
cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
script:
- bash ./compile_all.sh